// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVfPwjldJfAUTFIL9Hc9BejCXPxm-XxhY',
    appId: '1:591369990524:web:04a4f750d45d924a7bb4f9',
    messagingSenderId: '591369990524',
    projectId: 'employetask',
    authDomain: 'employetask.firebaseapp.com',
    storageBucket: 'employetask.appspot.com',
    measurementId: 'G-B6G99RZLS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9UWNgMYCREzUumT6sSOw0L0bZsb0lTuE',
    appId: '1:591369990524:android:028712307fe6a3da7bb4f9',
    messagingSenderId: '591369990524',
    projectId: 'employetask',
    storageBucket: 'employetask.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3QmuHIGavJKVBAi8RzG7k9VDQcV_6J4s',
    appId: '1:591369990524:ios:dae8f449139da4597bb4f9',
    messagingSenderId: '591369990524',
    projectId: 'employetask',
    storageBucket: 'employetask.appspot.com',
    iosBundleId: 'com.example.firebaseEmpTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3QmuHIGavJKVBAi8RzG7k9VDQcV_6J4s',
    appId: '1:591369990524:ios:91cb00ee91452f3f7bb4f9',
    messagingSenderId: '591369990524',
    projectId: 'employetask',
    storageBucket: 'employetask.appspot.com',
    iosBundleId: 'com.example.firebaseEmpTask.RunnerTests',
  );
}
